### ISSUE TITLE
Click Shape Game

### ISSUE THREAD

**Issue by Sivasanath06** [SiddharthaBhattacharjee/TimePassGames#30]
Hey @SiddharthaBhattacharjee I am creating a website based on a game by using HTML CSS and Js so I want you to give me a chance on posting it.
![demo](https://user-images.githubusercontent.com/100675167/194963185-b1368fc2-2d67-4df0-ad65-f012accd43b2.gif)

**Comment by SiddharthaBhattacharjee** [comment]
Your game looks nice, go ahead and create a PR, make sure to run a git pull to ensure you are committing to the latest version, and when you make a PR, include a link to your branch hosted on GitHub pages for review purposes.

**Comment by Sivasanath06** [comment]
Hey @SiddharthaBhattacharjee , Thanks for your reply can you please assign me in this so that I can go forward to upload.

**Comment by SiddharthaBhattacharjee** [comment]
I have assigned you to the issue.

**Comment by SiddharthaBhattacharjee** [comment]
Hey, Haven't gotten any PRs back from you. Are you still working o the issue you created? 
Your game is good to go, all you need to do is pull the latest updates from the repo, add your game, add your game to the home screen, host your forked branch on GitHub pages and share the link so that I can check if it is properly added to homepage or not.
We are waiting for your next PR, if there is no new PR from you in the next few days, we will have to close this issue.
Since your game is ready to go, following these steps and getting your PR merged won't take much time, we are waiting for the PR to close this issue.

**Comment by SiddharthaBhattacharjee** [comment]
@Sivasanath06 If you are facing difficulty to add the game to the home page, please pull the latest state of this repo and simply add your game folder to it and create a pull request, I will add the game to the home page later, just make sure you don't copy paste the folder, create a folder and copy paste the files in the folder.

**Comment by SiddharthaBhattacharjee** [comment]
Since there is no response from your side for 3 days now, We have decided to close this issue, if you want this issue to be reopened, please contact me.
